# Generated by Django 5.2.6 on 2025-09-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='nome',
            new_name='name',
        ),
    ]
